# Catálogo de dispositivos, procesadores y componentes.
# Esquema esperado por generador_respuestas.py:
#   nombre          : str  (modelo / producto)
#   marca           : str  (samsung | xiaomi | apple | qualcomm | mediatek | motorola)
#   gama            : str  (alta | media | baja | premium | barato | economico | caro)
#   atributos       : list (adjetivos / specs que el usuario puede pedir)
#   procesador      : str  (matchea con 'snapdragon', 'dimensity', 'exynos', etc.)
#   ram             : str  (texto libre, p.ej. '12gb')
#   almacenamiento  : str  (texto libre, p.ej. '256gb')
#   descripcion     : str  (justificación de la recomendación)
#   usos_optimos    : list (palabras que matchean con el complemento de uso)

DISPOSITIVOS = [

    # ────────────────────────────────────────────────────────────
    # GAMA ALTA — smartphones premium
    # ────────────────────────────────────────────────────────────
    {
        "nombre": "Samsung Galaxy S24 Ultra",
        "marca": "samsung",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido", "eficiente", "premium"],
        "procesador": "snapdragon 8 gen 3",
        "ram": "12gb",
        "almacenamiento": "512gb",
        "descripcion": "El flagship definitivo de Samsung con S-Pen integrado, cámara de 200 MP y el Snapdragon más potente del mercado. Ideal para gamers, creadores de contenido y profesionales que exigen el máximo rendimiento.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "edicion",
                         "trabajar", "trabajo", "estudio", "ocio", "diario", "premium"],
    },
    {
        "nombre": "Samsung Galaxy S24+",
        "marca": "samsung",
        "gama": "alta",
        "atributos": ["rapido", "potente", "fluido", "veloz", "eficiente"],
        "procesador": "exynos 2400",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "Versión Plus del S24 con pantalla AMOLED de 6.7 pulgadas y batería de 4900 mAh. Equilibrio perfecto entre tamaño, potencia y precio dentro de la gama alta.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo",
                         "estudio", "ocio", "diario"],
    },
    {
        "nombre": "Samsung Galaxy S23 Ultra",
        "marca": "samsung",
        "gama": "alta",
        "atributos": ["rapido", "potente", "fluido", "veloz"],
        "procesador": "snapdragon 8 gen 2",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "Generación anterior que sigue siendo una bestia. Cámara de 200 MP, S-Pen y rendimiento Snapdragon de primer nivel a un precio más accesible que el S24.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "estudio", "ocio"],
    },
    {
        "nombre": "Samsung Galaxy Z Fold 5",
        "marca": "samsung",
        "gama": "premium",
        "atributos": ["potente", "rapido", "fluido", "premium", "innovador"],
        "procesador": "snapdragon 8 gen 2",
        "ram": "12gb",
        "almacenamiento": "512gb",
        "descripcion": "Smartphone plegable de referencia. Pantalla interna de 7.6 pulgadas ideal para multitarea, productividad y consumir contenido multimedia en formato tablet.",
        "usos_optimos": ["programar", "desarrollo", "editar", "trabajo",
                         "trabajar", "estudio", "ocio", "diario", "premium"],
    },
    {
        "nombre": "Apple iPhone 15 Pro Max",
        "marca": "apple",
        "gama": "alta",
        "atributos": ["rapido", "potente", "fluido", "veloz", "eficiente", "premium"],
        "procesador": "apple a17 pro",
        "ram": "8gb",
        "almacenamiento": "256gb",
        "descripcion": "El iPhone más avanzado: chip A17 Pro con trazado de rayos por hardware, cuerpo de titanio y puerto USB-C. Excelente optimización iOS para juegos y edición de video profesional.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "editar", "edicion", "desarrollo", "trabajo",
                         "estudio", "ocio", "diario", "premium"],
    },
    {
        "nombre": "Apple iPhone 15 Pro",
        "marca": "apple",
        "gama": "alta",
        "atributos": ["rapido", "potente", "fluido", "veloz", "premium"],
        "procesador": "apple a17 pro",
        "ram": "8gb",
        "almacenamiento": "128gb",
        "descripcion": "Mismo chip A17 Pro que su hermano mayor en un cuerpo más compacto de 6.1 pulgadas. La mejor opción si prefieres iOS en un tamaño manejable.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "editar",
                         "desarrollo", "trabajo", "estudio", "ocio", "diario"],
    },
    {
        "nombre": "Apple iPhone 14 Pro",
        "marca": "apple",
        "gama": "alta",
        "atributos": ["rapido", "potente", "fluido", "veloz"],
        "procesador": "apple a16 bionic",
        "ram": "6gb",
        "almacenamiento": "128gb",
        "descripcion": "Generación anterior con Dynamic Island y cámara de 48 MP. Sigue siendo extremadamente capaz para juegos, fotografía y video en 4K.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "editar",
                         "trabajo", "estudio", "ocio", "diario"],
    },
    {
        "nombre": "Xiaomi 14 Ultra",
        "marca": "xiaomi",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido", "eficiente", "premium"],
        "procesador": "snapdragon 8 gen 3",
        "ram": "16gb",
        "almacenamiento": "512gb",
        "descripcion": "La joya de Xiaomi: cuádruple cámara Leica, Snapdragon 8 Gen 3 y carga inalámbrica de 80W. Pensado para entusiastas de la fotografía y power users.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "editar", "edicion", "desarrollo", "trabajo", "estudio", "ocio", "premium"],
    },
    {
        "nombre": "Xiaomi 14 Pro",
        "marca": "xiaomi",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido"],
        "procesador": "snapdragon 8 gen 3",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "Flagship compacto de Xiaomi con pantalla LTPO de 120Hz y óptica Leica. Gran relación rendimiento/precio dentro de la gama alta premium.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "editar",
                         "desarrollo", "trabajo", "estudio", "ocio", "diario"],
    },
    {
        "nombre": "Xiaomi 13T Pro",
        "marca": "xiaomi",
        "gama": "alta",
        "atributos": ["rapido", "potente", "fluido", "veloz"],
        "procesador": "dimensity 9200+",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "Cámara Leica, MediaTek Dimensity 9200+ y carga de 120W. Excelente opción si quieres potencia MediaTek de tope de gama a precio agresivo.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "emuladores",
                         "editar", "desarrollo", "trabajo", "estudio", "ocio"],
    },
    {
        "nombre": "Motorola Edge 50 Ultra",
        "marca": "motorola",
        "gama": "alta",
        "atributos": ["rapido", "potente", "fluido", "veloz", "premium"],
        "procesador": "snapdragon 8s gen 3",
        "ram": "12gb",
        "almacenamiento": "512gb",
        "descripcion": "El gama alta de Motorola con pantalla pOLED de 144Hz y carga TurboPower de 125W. Diseño en madera o vegan leather, único en su segmento.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "editar",
                         "desarrollo", "trabajo", "estudio", "ocio", "diario", "premium"],
    },

    # ────────────────────────────────────────────────────────────
    # GAMA MEDIA — mejor relación rendimiento/precio
    # ────────────────────────────────────────────────────────────
    {
        "nombre": "Samsung Galaxy A55 5G",
        "marca": "samsung",
        "gama": "media",
        "atributos": ["rapido", "fluido", "buena", "bueno", "eficiente"],
        "procesador": "exynos 1480",
        "ram": "8gb",
        "almacenamiento": "256gb",
        "descripcion": "Gama media premium de Samsung con pantalla Super AMOLED 120Hz y resistencia IP67. Excelente autonomía y soporte de actualizaciones de 5 años.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "programar",
                         "desarrollo", "editar", "trabajo", "estudio", "ocio", "diario"],
    },
    {
        "nombre": "Samsung Galaxy A35 5G",
        "marca": "samsung",
        "gama": "media",
        "atributos": ["fluido", "buena", "bueno", "rapido"],
        "procesador": "exynos 1380",
        "ram": "6gb",
        "almacenamiento": "128gb",
        "descripcion": "Equilibrio ideal entre precio y prestaciones para el día a día. Pantalla AMOLED 120Hz y buena autonomía en un diseño moderno.",
        "usos_optimos": ["jugar", "minecraft", "estudio", "trabajo", "ocio", "diario"],
    },
    {
        "nombre": "Samsung Galaxy A25 5G",
        "marca": "samsung",
        "gama": "media",
        "atributos": ["fluido", "bueno", "buena", "barato"],
        "procesador": "exynos 1280",
        "ram": "6gb",
        "almacenamiento": "128gb",
        "descripcion": "Gama media accesible de Samsung con pantalla Super AMOLED y One UI 6. Cumplidor para uso diario, redes sociales y multimedia.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "Xiaomi Redmi Note 13 Pro+ 5G",
        "marca": "xiaomi",
        "gama": "media",
        "atributos": ["rapido", "potente", "fluido", "buena", "bueno"],
        "procesador": "dimensity 7200 ultra",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "El gama media estrella de Xiaomi: cámara de 200 MP, carga HyperCharge de 120W y pantalla AMOLED curva. Difícil de superar en su rango.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "editar",
                         "desarrollo", "trabajo", "estudio", "ocio", "diario"],
    },
    {
        "nombre": "Xiaomi Redmi Note 13 Pro 5G",
        "marca": "xiaomi",
        "gama": "media",
        "atributos": ["rapido", "fluido", "buena", "bueno", "potente"],
        "procesador": "snapdragon 7s gen 2",
        "ram": "8gb",
        "almacenamiento": "256gb",
        "descripcion": "Snapdragon 7s Gen 2 con pantalla AMOLED 120Hz y cámara de 200 MP. Un todoterreno confiable para gaming casual y fotografía.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "estudio",
                         "trabajo", "ocio", "diario"],
    },
    {
        "nombre": "Xiaomi Redmi Note 13",
        "marca": "xiaomi",
        "gama": "media",
        "atributos": ["fluido", "bueno", "buena", "barato"],
        "procesador": "snapdragon 685",
        "ram": "8gb",
        "almacenamiento": "256gb",
        "descripcion": "Gama media económica con pantalla AMOLED 120Hz y carga rápida de 33W. Perfecto para estudiantes y uso diario sin gastar de más.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "Xiaomi Poco X6 Pro",
        "marca": "xiaomi",
        "gama": "media",
        "atributos": ["rapido", "potente", "fluido", "veloz", "barato"],
        "procesador": "dimensity 8300 ultra",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "El rey del性价比: Dimensity 8300-Ultra, pantalla AMOLED 120Hz y 12 GB de RAM por menos de la mitad de un flagship. Brutez en juegos y apps pesadas.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "estudio", "ocio"],
    },
    {
        "nombre": "Xiaomi Poco F6",
        "marca": "xiaomi",
        "gama": "media",
        "atributos": ["rapido", "potente", "fluido", "veloz", "barato"],
        "procesador": "snapdragon 8s gen 3",
        "ram": "8gb",
        "almacenamiento": "256gb",
        "descripcion": "Snapdragon 8s Gen 3 a precio de gama media. Ideal para gamers que buscan máximo rendimiento sin pagar flagship.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "ocio"],
    },
    {
        "nombre": "Motorola Edge 50 Fusion",
        "marca": "motorola",
        "gama": "media",
        "atributos": ["rapido", "fluido", "buena", "bueno", "veloz"],
        "procesador": "snapdragon 7s gen 2",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "Pantalla pOLED 144Hz, Snapdragon 7s Gen 2 y diseño IP68. Muy buena opción para creadores de contenido y multitarea.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "editar",
                         "desarrollo", "trabajo", "estudio", "ocio", "diario"],
    },
    {
        "nombre": "Motorola Moto G84 5G",
        "marca": "motorola",
        "gama": "media",
        "atributos": ["fluido", "bueno", "buena", "barato"],
        "procesador": "snapdragon 695",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "Excelente pantalla pOLED 120Hz y gran batería de 5000 mAh. Muy buena elección en gama media económica.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "Motorola Edge 40 Neo",
        "marca": "motorola",
        "gama": "media",
        "atributos": ["rapido", "fluido", "buena", "bueno", "veloz"],
        "procesador": "dimensity 7030",
        "ram": "12gb",
        "almacenamiento": "256gb",
        "descripcion": "Cuerpo ultrafino con IP68, pantalla pOLED 144Hz y Dimensity 7030. Muy buen rendimiento y experiencia multimedia.",
        "usos_optimos": ["jugar", "minecraft", "estudio", "trabajo", "ocio", "diario"],
    },

    # ────────────────────────────────────────────────────────────
    # GAMA BAJA — presupuesto ajustado
    # ────────────────────────────────────────────────────────────
    {
        "nombre": "Samsung Galaxy A15",
        "marca": "samsung",
        "gama": "baja",
        "atributos": ["bueno", "buena", "barato", "economico"],
        "procesador": "mediatek helio g99",
        "ram": "4gb",
        "almacenamiento": "128gb",
        "descripcion": "Smartphone económico con pantalla Super AMOLED 90Hz y triple cámara. Cumple sobrado para uso básico diario.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "Samsung Galaxy A05s",
        "marca": "samsung",
        "gama": "baja",
        "atributos": ["barato", "economico", "bueno"],
        "procesador": "snapdragon 680",
        "ram": "4gb",
        "almacenamiento": "128gb",
        "descripcion": "La opción más accesible de Samsung con Snapdragon y batería de 5000 mAh. Ideal como primer smartphone o para regalar.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "Xiaomi Redmi 13C",
        "marca": "xiaomi",
        "gama": "baja",
        "atributos": ["barato", "economico", "bueno", "buena"],
        "procesador": "mediatek helio g85",
        "ram": "4gb",
        "almacenamiento": "128gb",
        "descripcion": "El gama baja más vendido de Xiaomi. Batería de 5000 mAh, pantalla de 6.74\" y triple cámara a precio imbatible.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "Xiaomi Redmi A3",
        "marca": "xiaomi",
        "gama": "baja",
        "atributos": ["barato", "economico", "bueno"],
        "procesador": "mediatek helio g36",
        "ram": "3gb",
        "almacenamiento": "64gb",
        "descripcion": "Smartphone de entrada para llamadas, redes sociales y apps ligeras. Increíblemente económico sin sacrificar lo esencial.",
        "usos_optimos": ["estudio", "trabajo", "diario", "barato", "economico"],
    },
    {
        "nombre": "Motorola Moto G24",
        "marca": "motorola",
        "gama": "baja",
        "atributos": ["barato", "economico", "bueno", "fluido"],
        "procesador": "mediatek helio g85",
        "ram": "4gb",
        "almacenamiento": "128gb",
        "descripcion": "Gama baja con pantalla IPS 90Hz y Android 14. Diseño elegante y batería de 5000 mAh a precio muy bajo.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "Motorola Moto G14",
        "marca": "motorola",
        "gama": "baja",
        "atributos": ["barato", "economico", "bueno"],
        "procesador": "unisoc t616",
        "ram": "4gb",
        "almacenamiento": "128gb",
        "descripcion": "Opción ultra económica con buena autonomía y pantalla Full HD+. Pensado para uso básico y como segundo teléfono.",
        "usos_optimos": ["estudio", "trabajo", "diario", "barato", "economico"],
    },

    # ────────────────────────────────────────────────────────────
    # PROCESADORES — para requerimientos tipo "quiero un procesador snapdragon"
    # ────────────────────────────────────────────────────────────
    {
        "nombre": "Qualcomm Snapdragon 8 Gen 3",
        "marca": "qualcomm",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido", "eficiente", "premium"],
        "procesador": "snapdragon 8 gen 3",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "El SoC más potente de Qualcomm para 2024. CPU Kryo de 8 núcleos hasta 3.3 GHz, GPU Adreno 750 y NPU Hexagon para IA. Referencia en Android premium.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "edicion",
                         "trabajar", "trabajo", "premium"],
    },
    {
        "nombre": "Qualcomm Snapdragon 8 Gen 2",
        "marca": "qualcomm",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido"],
        "procesador": "snapdragon 8 gen 2",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Generación anterior de Qualcomm, aún muy vigente. CPU hasta 3.2 GHz, Adreno 740 y eficiencia energética excepcional.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "estudio"],
    },
    {
        "nombre": "Qualcomm Snapdragon 7+ Gen 2",
        "marca": "qualcomm",
        "gama": "media",
        "atributos": ["rapido", "potente", "fluido", "veloz", "barato"],
        "procesador": "snapdragon 7+ gen 2",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "El chipset favorito de la gama media-alta. Ofrece rendimiento casi flagship a precio de gama media.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "ocio"],
    },
    {
        "nombre": "Qualcomm Snapdragon 7s Gen 2",
        "marca": "qualcomm",
        "gama": "media",
        "atributos": ["rapido", "fluido", "bueno", "buena"],
        "procesador": "snapdragon 7s gen 2",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Snapdragon de gama media con litografía 4nm. Buen balance para gaming y multitarea en smartphones de precio contenido.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "estudio",
                         "trabajo", "ocio", "diario"],
    },
    {
        "nombre": "Qualcomm Snapdragon 695",
        "marca": "qualcomm",
        "gama": "media",
        "atributos": ["fluido", "bueno", "buena", "barato"],
        "procesador": "snapdragon 695",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Chipset 5G económico con buen rendimiento para tareas cotidianas. Muy común en gama media accesible.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
    {
        "nombre": "MediaTek Dimensity 9200+",
        "marca": "mediatek",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido", "premium"],
        "procesador": "dimensity 9200+",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "El flagship de MediaTek en 2023. CPU Cortex-X3 a 3.35 GHz y GPU Immortalis-G715. Rendimiento comparable al Snapdragon 8 Gen 2.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "ocio", "premium"],
    },
    {
        "nombre": "MediaTek Dimensity 8300 Ultra",
        "marca": "mediatek",
        "gama": "media",
        "atributos": ["rapido", "potente", "veloz", "fluido", "barato"],
        "procesador": "dimensity 8300 ultra",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Gama media premium de MediaTek en proceso 4nm. Ofrece rendimiento de flagship a precio de gama media.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "ocio"],
    },
    {
        "nombre": "MediaTek Dimensity 7050",
        "marca": "mediatek",
        "gama": "media",
        "atributos": ["fluido", "bueno", "buena", "barato"],
        "procesador": "dimensity 7050",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "SoC de gama media con buen rendimiento y eficiencia energética. Muy presente en smartphones de precio contenido.",
        "usos_optimos": ["jugar", "minecraft", "estudio", "trabajo", "ocio", "diario"],
    },
    {
        "nombre": "MediaTek Dimensity 7200 Ultra",
        "marca": "mediatek",
        "gama": "media",
        "atributos": ["rapido", "potente", "fluido", "buena"],
        "procesador": "dimensity 7200 ultra",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Chipset de 4nm con excelente relación rendimiento/consumo. Popular en gamas media premium.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "editar",
                         "desarrollo", "trabajo", "ocio"],
    },
    {
        "nombre": "Samsung Exynos 2400",
        "marca": "samsung",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido", "premium"],
        "procesador": "exynos 2400",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "SoC insignia de Samsung para 2024 con CPU de 10 núcleos y GPU Xclipse 940 (basada en AMD RDNA 3). Excelente en IA y juegos.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "programar", "desarrollo", "editar", "trabajo", "premium"],
    },
    {
        "nombre": "Samsung Exynos 1480",
        "marca": "samsung",
        "gama": "media",
        "atributos": ["rapido", "fluido", "buena", "bueno"],
        "procesador": "exynos 1480",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Chipset de gama media con GPU Xclipse 530 (AMD RDNA 2). Optimizado para gaming y fotografía computacional.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "estudio",
                         "trabajo", "ocio", "diario"],
    },
    {
        "nombre": "Samsung Exynos 1380",
        "marca": "samsung",
        "gama": "media",
        "atributos": ["fluido", "bueno", "buena"],
        "procesador": "exynos 1380",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Procesador de gama media con conectividad 5G y NPU mejorada. Excelente equilibrio para el día a día.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario"],
    },
    {
        "nombre": "Apple A17 Pro",
        "marca": "apple",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "fluido", "eficiente", "premium"],
        "procesador": "apple a17 pro",
        "ram": "—",
        "almacenamiento": "—",
        "descripcion": "Primer chip móvil de 3nm con trazado de rayos por hardware. CPU un 10% más rápida y GPU un 20% más potente que el A16.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "editar", "edicion", "desarrollo", "trabajo", "ocio", "premium"],
    },

    # ────────────────────────────────────────────────────────────
    # COMPONENTES — RAM y almacenamiento
    # ────────────────────────────────────────────────────────────
    {
        "nombre": "Memoria RAM 12 GB DDR5",
        "marca": "qualcomm",
        "gama": "alta",
        "atributos": ["rapida", "rapido", "potente", "buena", "bueno", "fluido", "veloz"],
        "procesador": "—",
        "ram": "12gb",
        "almacenamiento": "—",
        "descripcion": "Módulo de RAM LPDDR5X de 12 GB a 8533 Mbps. Pensado para multitarea pesada, edición de video y gaming con múltiples apps en segundo plano.",
        "usos_optimos": ["programar", "desarrollo", "editar", "edicion",
                         "jugar", "trabajo", "estudio", "premium"],
    },
    {
        "nombre": "Memoria RAM 8 GB LPDDR5",
        "marca": "qualcomm",
        "gama": "media",
        "atributos": ["rapida", "rapido", "buena", "bueno", "fluido"],
        "procesador": "—",
        "ram": "8gb",
        "almacenamiento": "—",
        "descripcion": "Módulo LPDDR5 de 8 GB. Estándar actual en gama media y muchos gama alta. Suficiente para casi todo el uso cotidiano y gaming.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "jugar", "minecraft"],
    },
    {
        "nombre": "Memoria RAM 16 GB LPDDR5X",
        "marca": "qualcomm",
        "gama": "alta",
        "atributos": ["rapida", "rapido", "potente", "fluido", "premium", "veloz"],
        "procesador": "—",
        "ram": "16gb",
        "almacenamiento": "—",
        "descripcion": "El tope de gama en RAM móvil. Ideal para usuarios power que mantienen decenas de apps abiertas y hacen edición profesional.",
        "usos_optimos": ["programar", "desarrollo", "editar", "edicion",
                         "jugar", "emuladores", "trabajo", "estudio", "premium"],
    },
    {
        "nombre": "Almacenamiento 512 GB UFS 4.0",
        "marca": "qualcomm",
        "gama": "alta",
        "atributos": ["rapido", "potente", "veloz", "premium", "buena"],
        "procesador": "—",
        "ram": "—",
        "almacenamiento": "512gb",
        "descripcion": "Almacenamiento UFS 4.0 con velocidades de hasta 4200 MB/s. Espacio de sobra para juegos pesados, video 4K y bibliotecas grandes.",
        "usos_optimos": ["jugar", "cod", "fortnite", "minecraft", "rdr", "emuladores",
                         "editar", "edicion", "desarrollo", "trabajo", "premium"],
    },
    {
        "nombre": "Almacenamiento 256 GB UFS 3.1",
        "marca": "qualcomm",
        "gama": "media",
        "atributos": ["rapido", "buena", "bueno", "fluido"],
        "procesador": "—",
        "ram": "—",
        "almacenamiento": "256gb",
        "descripcion": "El estándar más equilibrado: espacio suficiente para apps, fotos y video 4K sin quedarse corto, a un precio razonable.",
        "usos_optimos": ["jugar", "minecraft", "estudio", "trabajo", "ocio", "diario"],
    },
    {
        "nombre": "Almacenamiento 128 GB UFS 2.2",
        "marca": "qualcomm",
        "gama": "baja",
        "atributos": ["bueno", "buena", "barato", "economico"],
        "procesador": "—",
        "ram": "—",
        "almacenamiento": "128gb",
        "descripcion": "Almacenamiento base de 128 GB con velocidades decentes. Aceptable para uso básico, redes sociales y algunas apps.",
        "usos_optimos": ["estudio", "trabajo", "ocio", "diario", "barato", "economico"],
    },
]
